/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package session1.GUI;

import java.awt.Dialog;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import session1.dao.UserDao;
import session1.Entity.Users;
import session1.SharedData;

/**
 *
 * @author tienk
 */
public class GUILogin extends javax.swing.JFrame {

    private UserDao userDao = new UserDao();

    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        employLb = new javax.swing.JLabel();
        employTf = new javax.swing.JTextField();
        userLb = new javax.swing.JLabel();
        userTf = new javax.swing.JTextField();
        passLb = new javax.swing.JLabel();
        keepSignCb = new javax.swing.JCheckBox();
        showPassCb = new javax.swing.JCheckBox();
        passTf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        loginLb = new javax.swing.JLabel();
        noteLb = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(500, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employLb.setText("Employee:");
        getContentPane().add(employLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 67, -1));

        employTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employTfActionPerformed(evt);
            }
        });
        getContentPane().add(employTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 277, -1));

        userLb.setText("User:");
        getContentPane().add(userLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 67, -1));

        userTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTfActionPerformed(evt);
            }
        });
        getContentPane().add(userTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 277, -1));

        passLb.setText("Password:");
        getContentPane().add(passLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 67, -1));

        keepSignCb.setText("Keep me signed in");
        getContentPane().add(keepSignCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        showPassCb.setText("Show password");
        showPassCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCbActionPerformed(evt);
            }
        });
        getContentPane().add(showPassCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));
        getContentPane().add(passTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 277, -1));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        loginLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        loginLb.setText("LOGIN");
        getContentPane().add(loginLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, 50));

        noteLb.setText("Don't have an account?");
        getContentPane().add(noteLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        registerBtn.setText("Create one");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employTfActionPerformed

    private void userTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTfActionPerformed

    private void showPassCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCbActionPerformed
        JCheckBox checkbox = (JCheckBox) evt.getSource();
        passTf.setEchoChar(checkbox.isSelected() ? '\u0000' : '*');
    }//GEN-LAST:event_showPassCbActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        try {
            List<Users> users = userDao.getUsers();
            for (Users u : users) {
                if (u.getUserTypeID().getId() == 1 && employTf.getText().equals(u.getUsername()) && new String(passTf.getPassword()).equals(u.getPassword()) && userTf.getText().isEmpty()) {
                    SharedData.getInstance().setUsername(employTf.getText());

                    JOptionPane.showMessageDialog(null, "Success!", "LOGIN SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    new GUIManagement().setVisible(true);
                    dispose();
                } else if (u.getUserTypeID().getId() == 2 && userTf.getText().equals(u.getUsername()) && new String(passTf.getPassword()).equals(u.getPassword()) && employTf.getText().isEmpty()) {
                    SharedData.getInstance().setUsername(employTf.getText());

                    JOptionPane.showMessageDialog(null, "Success!", "LOGIN SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    new GUIManagement().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error!", "INVALID", JOptionPane.ERROR);

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(GUILogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        new GUIRegister().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employLb;
    private javax.swing.JTextField employTf;
    private javax.swing.JButton exitBtn;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JCheckBox keepSignCb;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginLb;
    private javax.swing.JLabel noteLb;
    private javax.swing.JLabel passLb;
    private javax.swing.JPasswordField passTf;
    private javax.swing.JButton registerBtn;
    private javax.swing.JCheckBox showPassCb;
    private javax.swing.JLabel userLb;
    private javax.swing.JTextField userTf;
    // End of variables declaration//GEN-END:variables
}
