/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package session1.GUI;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import session1.Entity.Items;
import session1.dao.ItemsDao;

/**
 *
 * @author tienk
 */
public class GUIManagement extends javax.swing.JFrame {
    private ItemsDao itemsDao = new ItemsDao();
    private DefaultTableModel defaut = new DefaultTableModel();
    /**
     * Creates new form GUIManagement
     */
    public GUIManagement() {
        initComponents();
        List<Items> items = itemsDao.findCustom();
        
        manageTable.setModel(defaut);
        ownerTable.setModel(defaut);
        defaut.addColumn("Title");
        defaut.addColumn("Capacity");
        defaut.addColumn("Area");
        defaut.addColumn("Type");
        
        for(Items i : items) {
            defaut.addRow(new Object[]{i.getTitle(), i.getCapacity(), i.getAreaID().getId(), i.getItemTypeID().getName()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageLb = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        paneTraver = new javax.swing.JPanel();
        searchTf = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        manageTable = new javax.swing.JTable();
        searchBtn = new javax.swing.JButton();
        paneOwner = new javax.swing.JPanel();
        scrollPane1 = new javax.swing.JScrollPane();
        ownerTable = new javax.swing.JTable();
        addListingBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageLb.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        manageLb.setText("Management Form");

        searchTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchTf.setText("       Search destination or Listing tittle or Attraction");
        searchTf.setBorder(null);
        searchTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTfActionPerformed(evt);
            }
        });

        manageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title ", "Capacity", "Area", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(manageTable);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneTraverLayout = new javax.swing.GroupLayout(paneTraver);
        paneTraver.setLayout(paneTraverLayout);
        paneTraverLayout.setHorizontalGroup(
            paneTraverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTraverLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(paneTraverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneTraverLayout.createSequentialGroup()
                        .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        paneTraverLayout.setVerticalGroup(
            paneTraverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTraverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTraverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTf, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabPane.addTab("I'm Traveler", paneTraver);

        ownerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title ", "Capacity", "Area", "Type", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane1.setViewportView(ownerTable);

        addListingBtn.setText("+ Add Listing");
        addListingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneOwnerLayout = new javax.swing.GroupLayout(paneOwner);
        paneOwner.setLayout(paneOwnerLayout);
        paneOwnerLayout.setHorizontalGroup(
            paneOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOwnerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(addListingBtn)
                .addContainerGap(767, Short.MAX_VALUE))
            .addGroup(paneOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneOwnerLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        paneOwnerLayout.setVerticalGroup(
            paneOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOwnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addListingBtn)
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(paneOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneOwnerLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        tabPane.addTab("I'm Owner / Manager", paneOwner);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutBtn)
                        .addGap(41, 41, 41)
                        .addComponent(exitBtn)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(294, 294, 294)
                            .addComponent(manageLb))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageLb)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(exitBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new GUILogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void searchTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTfActionPerformed
        
    }//GEN-LAST:event_searchTfActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        defaut.setRowCount(0);
        
        List<Items> items = itemsDao.findByTitle(searchTf.getText());
        for(Items i : items) {
            defaut.addRow(new Object[]{i.getTitle(), i.getCapacity(), i.getAreaID().getId(), i.getItemTypeID().getName()});
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addListingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListingBtnActionPerformed
        new GUIAddListing().setVisible(true);
        dispose();
    }//GEN-LAST:event_addListingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addListingBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel manageLb;
    private javax.swing.JTable manageTable;
    private javax.swing.JTable ownerTable;
    private javax.swing.JPanel paneOwner;
    private javax.swing.JPanel paneTraver;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTf;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
