/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package session1.GUI;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session1.Entity.Users;
import session1.Entity.Usertypes;
import session1.dao.UserDao;
import session1.dao.UsersTypeDao;

/**
 *
 * @author tienk
 */
public class GUIRegister extends javax.swing.JFrame {

    private UserDao userDao = new UserDao();
    private UsersTypeDao userType = new UsersTypeDao();
    /**
     * Creates new form GUIRegister
     */
    public GUIRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerLb = new javax.swing.JLabel();
        userLb = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        birthdayLb = new javax.swing.JLabel();
        userTf = new javax.swing.JTextField();
        nameTf = new javax.swing.JTextField();
        birthdayTf = new javax.swing.JTextField();
        GroupGerder = new javax.swing.JPanel();
        maleCb = new javax.swing.JCheckBox();
        femaleCb = new javax.swing.JCheckBox();
        familySp = new javax.swing.JSpinner();
        familyLb = new javax.swing.JLabel();
        passLb = new javax.swing.JLabel();
        retypePassLb = new javax.swing.JLabel();
        agreeTermCb = new javax.swing.JCheckBox();
        registerBtn = new javax.swing.JButton();
        backLoginBtn = new javax.swing.JButton();
        passPf = new javax.swing.JPasswordField();
        retypePassPf = new javax.swing.JPasswordField();
        termLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerLb.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        registerLb.setText("Create account");

        userLb.setText("Username:");

        nameLb.setText("Full name:");

        birthdayLb.setText("Birthday:");

        userTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTfActionPerformed(evt);
            }
        });

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        birthdayTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayTfActionPerformed(evt);
            }
        });

        maleCb.setText("Male");
        maleCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCbActionPerformed(evt);
            }
        });

        femaleCb.setText("Female");
        femaleCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GroupGerderLayout = new javax.swing.GroupLayout(GroupGerder);
        GroupGerder.setLayout(GroupGerderLayout);
        GroupGerderLayout.setHorizontalGroup(
            GroupGerderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupGerderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(maleCb)
                .addGap(18, 18, 18)
                .addComponent(femaleCb)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        GroupGerderLayout.setVerticalGroup(
            GroupGerderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GroupGerderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(GroupGerderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleCb)
                    .addComponent(femaleCb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        familySp.setToolTipText("");

        familyLb.setText("Number of Family Members: ");

        passLb.setText("Password:");

        retypePassLb.setText("Retype password:");

        agreeTermCb.setText("I agree to the terms and conditions");
        agreeTermCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeTermCbActionPerformed(evt);
            }
        });

        registerBtn.setText("Register & login");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        backLoginBtn.setText("Return login form");
        backLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginBtnActionPerformed(evt);
            }
        });

        passPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPfActionPerformed(evt);
            }
        });

        termLb.setText("View Term and Conditions");
        termLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        termLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termLbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerLb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passLb)
                                .addGap(43, 43, 43)
                                .addComponent(passPf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userLb)
                                    .addComponent(nameLb)
                                    .addComponent(birthdayLb))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(birthdayTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(agreeTermCb))
                        .addGap(129, 129, 129)))
                .addGap(21, 21, 21)
                .addComponent(GroupGerder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(familyLb)
                        .addGap(18, 18, 18)
                        .addComponent(familySp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(termLb)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backLoginBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(retypePassLb)
                                .addGap(18, 18, 18)
                                .addComponent(retypePassPf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(registerLb)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GroupGerder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(birthdayLb)
                                    .addComponent(birthdayTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userLb))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLb)
                                    .addComponent(familySp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(familyLb))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypePassLb)
                    .addComponent(passLb)
                    .addComponent(passPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retypePassPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agreeTermCb)
                    .addComponent(termLb))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(backLoginBtn))
                .addGap(61, 61, 61))
        );

        familySp.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTfActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void birthdayTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayTfActionPerformed

    private void maleCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCbActionPerformed
        if (maleCb.isSelected()) {
            femaleCb.setSelected(false);
        }
    }//GEN-LAST:event_maleCbActionPerformed

    private void femaleCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleCbActionPerformed
        if (femaleCb.isSelected()) {
            maleCb.setSelected(false);
        }
    }//GEN-LAST:event_femaleCbActionPerformed

    private void agreeTermCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeTermCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agreeTermCbActionPerformed

    private void backLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginBtnActionPerformed
        new GUILogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_backLoginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        Users u = new Users();
        try {
            u.setId(userDao.getUsers().get(userDao.getUsers().size() - 1).getId() + 1);
        } catch (Exception ex) {
            Logger.getLogger(GUIRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            u.setUserTypeID(userType.getUsertypes("user"));
        } catch (SQLException ex) {
            Logger.getLogger(GUIRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        u.setUsername(userTf.getText());
        u.setPassword((new String(passPf.getPassword())).equals(new String(retypePassPf.getPassword())) ? (new String(passPf.getPassword())) : "123456");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            u.setBirthDate(sdf.parse(birthdayTf.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(GUIRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        u.setFullName(nameTf.getText());
        u.setFamilyCount((int) familySp.getValue());
        u.setGender(maleCb.isSelected());
        u.setGuid(UUID.randomUUID().toString());
        userDao.addUsers(u);
        JOptionPane.showMessageDialog(null, "Success!", "REGISTER SUCCESS", JOptionPane.INFORMATION_MESSAGE);
        new GUIManagement().setVisible(true);
        dispose();
    }//GEN-LAST:event_registerBtnActionPerformed

    private void passPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPfActionPerformed
    
    private void termLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termLbMouseClicked

        try {
            Desktop.getDesktop().open(new File("C:\\Users\\tienk\\OneDrive\\Documents\\Code\\Thi_Tay_Nghe\\2023HANOI_Skills (GPPM CNTT)\\2023HANOI_Skills (GPPM CNTT)\\DataFiles\\WSC2022SE_TP09_Session1_actual_en\\Terms.txt"));
        } catch (IOException ex) {
            Logger.getLogger(GUIRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_termLbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GroupGerder;
    private javax.swing.JCheckBox agreeTermCb;
    private javax.swing.JButton backLoginBtn;
    private javax.swing.JLabel birthdayLb;
    private javax.swing.JTextField birthdayTf;
    private javax.swing.JLabel familyLb;
    private javax.swing.JSpinner familySp;
    private javax.swing.JCheckBox femaleCb;
    private javax.swing.JCheckBox maleCb;
    private javax.swing.JLabel nameLb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel passLb;
    private javax.swing.JPasswordField passPf;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerLb;
    private javax.swing.JLabel retypePassLb;
    private javax.swing.JPasswordField retypePassPf;
    private javax.swing.JLabel termLb;
    private javax.swing.JLabel userLb;
    private javax.swing.JTextField userTf;
    // End of variables declaration//GEN-END:variables
}
