/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package session4.GUI;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import session4.dao.AmenityDAO;
import session4.dao.AreaDAO;
import session4.dao.AttractionDAO;
import session4.dao.BookingDAO;
import session4.dao.ItemTypeDAO;
import session4.dao.ItemsDAO;
import session4.dao.ScoreDAO;
import session4.entity.Amenities;
import session4.entity.Areas;
import session4.entity.Attractions;
import session4.entity.Bookings;
import session4.entity.Items;
import session4.entity.Itemscores;
import session4.entity.Itemtypes;

/**
 *
 * @author tienk
 */
public class GUISearch extends javax.swing.JFrame {

    private ItemsDAO itemsDAO = new ItemsDAO();
    private BookingDAO bookingDAO = new BookingDAO();
    private ScoreDAO scoreDAO = new ScoreDAO();
    private AmenityDAO amenityDAO = new AmenityDAO();
    private AttractionDAO attractionDAO = new AttractionDAO();
    private AreaDAO areaDAO = new AreaDAO();
    private ItemTypeDAO typeDAO = new ItemTypeDAO();
    private DefaultTableModel defaut = new DefaultTableModel();    /**
     * Creates new form GUISearch
     */
    public GUISearch() {
        initComponents();
        searchTable.setModel(defaut);
        defaut.addColumn("Property");
        defaut.addColumn("Area");
        defaut.addColumn("Average");
        defaut.addColumn("Total completed reservations");
        defaut.addColumn("Amount payable");
        defaut.addColumn("Check-in at");
        List<Items> items = itemsDAO.findAll();
        List<Attractions> attractionses = attractionDAO.findAll();
        List<Areas> areases = areaDAO.findAll();
        List<Amenities> amenitiess = amenityDAO.findAll();
        List<Itemtypes> types = typeDAO.findAll();
        for(Items i : items) {
            titleCbb.addItem(i.getTitle());
        }
        
        for(Attractions i : attractionses) {
            attractCbb.addItem(i.getName());
        }
        for(Areas i : areases) {
            areaCbb.addItem(i.getName());
        }
        for(Amenities i : amenitiess) {
            ameCbb1.addItem(i.getName());
            ameCbb2.addItem(i.getName());
            ameCbb3.addItem(i.getName());
        }
        for(Itemtypes i : types) {
            typeCbb.addItem(i.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        searchTab = new javax.swing.JTabbedPane();
        simpleSearchTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTf = new javax.swing.JTextField();
        dateTf = new javax.swing.JTextField();
        dateLb = new javax.swing.JLabel();
        forLb = new javax.swing.JLabel();
        nightSpin = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        peopleSpin = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        searchBtn1 = new javax.swing.JButton();
        advBtn = new javax.swing.JButton();
        advancedSearchTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        areaCbb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        attractCbb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        titleCbb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dateFromTf = new javax.swing.JTextField();
        dateLb1 = new javax.swing.JLabel();
        dateToTf = new javax.swing.JTextField();
        forLb1 = new javax.swing.JLabel();
        nightSpin2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        peopleSpin2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        minPriceSpin = new javax.swing.JSpinner();
        maxPriceSpin = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        typeCbb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ameCbb1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ameCbb2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ameCbb3 = new javax.swing.JComboBox<>();
        simpleSearch = new javax.swing.JButton();
        clearFormBtn = new javax.swing.JButton();
        searchBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Property", "Area", "Average", "Total completed reservations", "Amount payable", "Check-in at"
            }
        ));
        jScrollPane1.setViewportView(searchTable);
        if (searchTable.getColumnModel().getColumnCount() > 0) {
            searchTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            searchTable.getColumnModel().getColumn(1).setPreferredWidth(10);
            searchTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 879, 393));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Simple search");

        searchTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchTf.setText("Seoul Tower");
        searchTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTfActionPerformed(evt);
            }
        });

        dateLb.setText("From:");

        forLb.setText("for");

        jLabel2.setText("nights       and");

        jLabel3.setText("people");

        searchBtn1.setText("Seach properties");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        advBtn.setText("Advance search");
        advBtn.setToolTipText("");
        advBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout simpleSearchTabLayout = new javax.swing.GroupLayout(simpleSearchTab);
        simpleSearchTab.setLayout(simpleSearchTabLayout);
        simpleSearchTabLayout.setHorizontalGroup(
            simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleSearchTabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(simpleSearchTabLayout.createSequentialGroup()
                        .addGroup(simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(simpleSearchTabLayout.createSequentialGroup()
                                .addComponent(dateLb)
                                .addGap(18, 18, 18)
                                .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(forLb)
                                .addGap(29, 29, 29)
                                .addComponent(nightSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(peopleSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3))
                            .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(advBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        simpleSearchTabLayout.setVerticalGroup(
            simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn1))
                .addGap(18, 18, 18)
                .addGroup(simpleSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLb)
                    .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forLb)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nightSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peopleSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advBtn))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        searchTab.addTab("tab1", simpleSearchTab);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Advance Search");

        jLabel5.setText("Area:");

        jLabel6.setText("Attraction:");

        jLabel7.setText("Property title:");

        jLabel8.setText("From:");

        dateFromTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFromTfActionPerformed(evt);
            }
        });

        dateLb1.setText("To:");

        forLb1.setText("for");

        jLabel9.setText("nights       and");

        jLabel10.setText("people");

        jLabel11.setText("Starting price:");

        jLabel12.setText("Maximum price:");

        jLabel13.setText("Property type:");

        jLabel14.setText("Amenity:");

        jLabel15.setText("Amenity:");

        jLabel16.setText("Amenity:");

        simpleSearch.setText("Simple Search");
        simpleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleSearchActionPerformed(evt);
            }
        });

        clearFormBtn.setText("Clear form");
        clearFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormBtnActionPerformed(evt);
            }
        });

        searchBtn2.setText("Search properties");
        searchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout advancedSearchTabLayout = new javax.swing.GroupLayout(advancedSearchTab);
        advancedSearchTab.setLayout(advancedSearchTabLayout);
        advancedSearchTabLayout.setHorizontalGroup(
            advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedSearchTabLayout.createSequentialGroup()
                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateFromTf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(dateLb1)
                                .addGap(18, 18, 18)
                                .addComponent(dateToTf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(forLb1)
                                .addGap(29, 29, 29)
                                .addComponent(nightSpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(peopleSpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel10))
                            .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(ameCbb1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(ameCbb2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(areaCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(attractCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(titleCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advancedSearchTabLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advancedSearchTabLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)
                                                .addComponent(ameCbb3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(searchBtn2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advancedSearchTabLayout.createSequentialGroup()
                                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(minPriceSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maxPriceSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                        .addGap(461, 461, 461)
                                        .addComponent(simpleSearch)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearFormBtn)
                                    .addGroup(advancedSearchTabLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(typeCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        advancedSearchTabLayout.setVerticalGroup(
            advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(areaCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(attractCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(titleCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dateFromTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLb1)
                    .addComponent(dateToTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forLb1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(nightSpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peopleSpin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(minPriceSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(maxPriceSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(typeCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ameCbb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(ameCbb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ameCbb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advancedSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpleSearch)
                    .addComponent(clearFormBtn)
                    .addComponent(searchBtn2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        searchTab.addTab("tab2", advancedSearchTab);

        getContentPane().add(searchTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, 980, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateFromTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFromTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFromTfActionPerformed

    private void clearFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearFormBtnActionPerformed

    private void searchBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn2ActionPerformed
        searchBtn1ActionPerformed(evt);
    }//GEN-LAST:event_searchBtn2ActionPerformed

    private void advBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advBtnActionPerformed
        searchTab.setSelectedIndex((searchTab.getSelectedIndex() + 1) % searchTab.getTabCount());
    }//GEN-LAST:event_advBtnActionPerformed

    private void simpleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleSearchActionPerformed
        searchTab.setSelectedIndex((searchTab.getSelectedIndex() + 1) % searchTab.getTabCount());
    }//GEN-LAST:event_simpleSearchActionPerformed

    private void searchTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTfActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        defaut.setRowCount(0);
        String key = searchTf.getText();
        int night = (Integer) nightSpin.getValue();
        int capacity = (Integer) peopleSpin.getValue();
        
        List<Items> items;
        if(searchTab.getSelectedIndex() == 0) {
            items = itemsDAO.findItemsCustom(capacity, night, key);
        } else {
            items = itemsDAO.findItemsCustom2(capacity, night, (String )titleCbb.getSelectedItem(), (String) areaCbb.getSelectedItem(), (String) typeCbb.getSelectedItem(), (String) attractCbb.getSelectedItem(), (String) ameCbb1.getSelectedItem() + (String) ameCbb2.getSelectedItem() + (String) ameCbb3.getSelectedItem());
        }
       
       

        if(items.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Not found", "Not found item", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for(Items i : items) {
                List<Itemscores> scores = scoreDAO.findById(i.getId());
                List<Bookings> bookings = bookingDAO.findBookingsCustom(i.getId());
                
                double avg = 0;
                if(!scores.isEmpty()) {
                    for(Itemscores score : scores) {
                        avg += score.getValue();
                    }
                    avg /= scores.size();
                }
                double paid = 0;
                if(!bookings.isEmpty()) {
                    for(Bookings booking : bookings) {
                        paid += booking.getAmountPaid().doubleValue();
                    }
             
                }
                
                defaut.addRow(new Object[]{i.getTitle(), i.getAreaID().getName(), avg, bookings.size(), paid});
            }
            
        }
        
    }//GEN-LAST:event_searchBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advBtn;
    private javax.swing.JPanel advancedSearchTab;
    private javax.swing.JComboBox<String> ameCbb1;
    private javax.swing.JComboBox<String> ameCbb2;
    private javax.swing.JComboBox<String> ameCbb3;
    private javax.swing.JComboBox<String> areaCbb;
    private javax.swing.JComboBox<String> attractCbb;
    private javax.swing.JButton clearFormBtn;
    private javax.swing.JTextField dateFromTf;
    private javax.swing.JLabel dateLb;
    private javax.swing.JLabel dateLb1;
    private javax.swing.JTextField dateTf;
    private javax.swing.JTextField dateToTf;
    private javax.swing.JLabel forLb;
    private javax.swing.JLabel forLb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner maxPriceSpin;
    private javax.swing.JSpinner minPriceSpin;
    private javax.swing.JSpinner nightSpin;
    private javax.swing.JSpinner nightSpin2;
    private javax.swing.JSpinner peopleSpin;
    private javax.swing.JSpinner peopleSpin2;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JButton searchBtn2;
    private javax.swing.JTabbedPane searchTab;
    private javax.swing.JTable searchTable;
    private javax.swing.JTextField searchTf;
    private javax.swing.JButton simpleSearch;
    private javax.swing.JPanel simpleSearchTab;
    private javax.swing.JComboBox<String> titleCbb;
    private javax.swing.JComboBox<String> typeCbb;
    // End of variables declaration//GEN-END:variables
}
